config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions:  'users/sessions',
    registrations: 'users/registrations'
  }


  get 'prousts/about', as: :about

  get 'prousts/new'
  get 'prousts/:id/show', to: 'prousts#show', as: :proust_show
  get 'prousts/:id/common_posts_index', to: 'prousts#common_posts_index'
  get 'prousts/:id/common_posts_show', to: 'prousts#common_posts_show'
  get '/', to: 'prousts#map', as: :map

  post 'prousts/create', as: :proust

  post 'prousts/convert'

  delete '/prousts/:id/delete', to: 'prousts#destroy', as: :proust_delete

end

app/controllers/prousts_controller.rb
require 'uri'
require 'net/http'
require 'openssl'
require 'digest/md5'
require 'date'
require 'fileutils'
require 'aws-sdk'

class ProustsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, except: [:about]
  before_action :ensure_correct_user, only: %i[show destroy]

  def about; end

  def new
    @params_post_info = Post.new

    @params_post_address = address_params['address']
    @params_post_latitude = address_params['latitude']
    @params_post_longitude = address_params['longitude']
    @params_post_artist = address_params['artist']
    @params_post_album = address_params['album']
    @params_post_songs_title = address_params['songs_title']
    @params_post_release_date = address_params['release_date']
    @params_post_youtube_link = address_params['youtube_link']

    @params_post_artwork = if address_params['artwork'].empty?
                             '/images/168410.jpg'
                           else
                             address_params['artwork']
                           end
  end

  def create
    @params_post_info = Post.new(post_params)
    @params_post_info.user_id = current_user.id
    @params_post_address = post_params['address']
    @params_post_latitude = post_params['latitude']
    @params_post_longitude = post_params['longitude']
    @params_post_artist = post_params['artist']
    @params_post_album = post_params['album']
    @params_post_songs_title = post_params['songs_title']
    @params_post_release_date = post_params['release_date']
    @params_post_youtube_link = post_params['youtube_link']

    @params_post_artwork = if post_params['artwork'].empty?
                             '/images/168410.jpg'
                           else
                             post_params['artwork']
                           end

    if @params_post_info.save
      redirect_to map_path
    else
      render 'prousts/new'
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to map_path
  end

  def map
    @posts = Post.where(user_id: current_user.id).order(created_at: :desc)
    gon.posts = Post.where(user_id: current_user.id)
    gon.post = Post.where(user_id: current_user.id).last

    @scroll_posts = Post.where(user_id: current_user.id).order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @post = Post.find(params[:id])
    v_param = @post.youtube_link.match(/v=.*$/).to_s
    @video_id = v_param.slice!(2..-1)
    songs_title = Post.find(params[:id]).songs_title
    @common_posts = Post.where.not(user_id: current_user.id).where(songs_title: songs_title)
  end

  def common_posts_index
    songs_title = Post.find(params[:id]).songs_title
    gon.common_posts = Post.where.not(user_id: current_user.id).where(songs_title: songs_title)
    @common_posts = Post.where.not(user_id: current_user.id).where(songs_title: songs_title)
    @scroll_common_posts = Post.where.not(user_id: current_user.id).where(songs_title: songs_title).page(params[:page]).per(9)
    @common_post = Post.find(params[:id])
  end

  def common_posts_show
    @post = Post.find(params[:id])
  end

  def convert
    params_file = params[:file]
    file_name = Digest::MD5.hexdigest(Time.zone.now.to_s)
    wav_file_name = file_name + '.wav'
    mp3_file_name = file_name + '.mp3'
    wav_file_path = Rails.root.to_s + '/tmp/songs/' + wav_file_name
    mp3_file_path = Rails.root.to_s + '/tmp/songs/' + mp3_file_name

    File.open(wav_file_path, 'wb') do |f|
      f.write(params_file.tempfile.read.force_encoding('UTF-8'))
    end

    system('ffmpeg -i "' + wav_file_path + '" -vn -ac 2 -ar 44100 -ab 256k -acodec libmp3lame -f mp3 "' + mp3_file_path + '"')

    # AWS upload
    region = 'ap-northeast-1'
    Aws.config.update(
      credentials: Aws::Credentials.new(Rails.application.credentials.aws[:access_key_id], Rails.application.credentials.aws[:secret_access_key])
    )

    s3 = Aws::S3::Resource.new(region: region)

    file = "#{Rails.root}/tmp/songs/#{mp3_file_name}"
    bucket = 'proust-songs-database'

    # Get just the file name
    name = File.basename(file)

    # Create the object to upload
    obj = s3.bucket(bucket).object(name)

    # Upload it
    obj.upload_file(file)

    # Delete WAV MP3 File
    FileUtils.rm(wav_file_path)
    FileUtils.rm(mp3_file_path)

    # Create a S3 client
    client = Aws::S3::Client.new(region: region)

    # オブジェクトの既定 ACL の設定
    object_key = name
    object_path = "http://#{bucket}.s3-ap-northeast-1.amazonaws.com/#{object_key}"

    client.put_object_acl(
      acl: 'public-read',
      bucket: bucket,
      key: object_key
    )

    # audDからjsonを取得
    url = URI("https://audd.p.rapidapi.com/?return=timecode%2Capple_music%2Cspotify%2Cdeezer%2Clyrics&spotify_country=ja&url=#{object_path}")

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE

    request = Net::HTTP::Get.new(url)
    request['x-rapidapi-host'] = Rails.application.credentials.audd[:x_rapidapi_host]
    request['x-rapidapi-key'] = Rails.application.credentials.audd[:x_rapidapi_key]

    response = http.request(request)

    # 詳細見る必要あり
    @result = JSON.parse(response.read_body)

    render json: @result
  end

  private

  def ensure_correct_user
    post = Post.find(params[:id])
    redirect_to map_path if post.user_id != current_user.id
  end

  def address_params
    params.permit(
      :address,
      :latitude,
      :longitude,
      :artist,
      :songs_title,
      :album,
      :release_date,
      :artwork,
      :youtube_link,
      :body,
      :post_image
    )
  end

  def post_params
    params.require(:post).permit(
      :user_id,
      :address,
      :latitude,
      :longitude,
      :artist,
      :songs_title,
      :album,
      :release_date,
      :artwork,
      :youtube_link,
      :body,
      :post_image
    )
  end
end

app/helpers/prousts_helper.rb
module ProustsHelper
end

app/views/prousts/_sidebar.html.erb
<div class="col-lg-2 mt-5 px-auto">
  <div class="d-inline-block">
    <p class="h2"><%= link_to common_post.songs_title, proust_show_path, :style => "color: #000;" %>
    <p><%= common_post.artist %></p>
    <img src="<%= common_post.artwork %>" width="210" height="210" alt="artiwork">
  </div>
</div>

app/views/prousts/about.html.erb
<% if user_signed_in? %>
  <%= render "shared/header_user_after_signin" %>
<% else %>
  <%= render "shared/header_user_before_signin" %>
<% end %>

<div class="jumbotron jumbotron-fluid">
  <div class="container" style="text-align: center">
    <h1 class="display-2 mb-4">Welcome to Proust!</h1>
    <p class="lead"><span class="h4 font-weight-normal">Proust</span>は音楽を聴いた時に感じた感動を、思い出として保存していけるWebサイトです。</p>
  </div>
</div>
<div class="container">
  <h3 class="display-4 mb-5">How to use Proust</h3>
  <h4 class="mb-3" style="font-size: 28px;">・Save Memories</h4>
  <div class="row mb-5">
    <div class="col-lg-3" style="text-align: center;">
      <%= image_tag '/images/proust_btn.png', :size =>'150x150' %>
      <div>
      <span class="text-primary"><em>Click This Button!</em></span>
      </div>
    </div>
    <div class="col-lg-9 pt-3">
      <p>街を歩いている時やカフェで休んでいる時のようなふとした瞬間。<br>聴こえてきた曲に感動したら<span class="text-primary"><em>このボタン</em></span>を押してください。</p>
      <p>ボタンを押すと、マイクと、位置情報サービスの、使用許可を確認されます。<br>許可をすると、音声の録音と位置情報の取得が行われ、データの取得が成功すると投稿画面が表示されます。
      <p>その時に感じたことや、観ていた風景などの写真を入力して、思い出を保存していきましょう！</p>
    </div>
  </div>
  <h4 class="mb-3" style="font-size: 28px;">・Proust Friends!</h4>
  <div class="row mb-5">
    <p class="ml-5">
      自分が投稿した曲と同じ曲の投稿をしているユーザーがいた場合、投稿詳細画面に<span class="text-primary">Proust Friends!</span>というリンクが表示されます。<br>
      リンク先では、詳細で見ていた曲についての他のユーザーの投稿を見ることができます。
    </p>
    <p class="ml-5">
      同じ曲の思い出を持っている仲間が、どこでどんなことを感じたのかを見て、楽しみましょう！
    </p>
    <%= image_tag '/images/proust_friends.png', style: "width: 100%; height: auto;" %>
  </div>
</div>

app/views/prousts/common_posts_show.html.erb
<%= render "shared/header_user_after_signin" %>

<%= @post.user.id %>

<%= @post.songs_title %>

<%= @post.artist %>

<%= @post.address %>

<%= @post.body %>

app/views/prousts/map.html.erb
<%= render "shared/header_user_after_signin" %>
<style>
  #sample {
    height: 94vh;
  }


  .nav-pills .nav-link {
    border-radius: 0 !important;
    width: 40px;
    height: 40px;
  }

  .nav-link {
    padding-left: 12px !important;
    padding-top: 7px;
  }



</style>

<!-- nav-pils -->
<ul class="nav nav-pills" id="myTab" role="tablist">
  <li class="nav-item nav-map bg-white" style="position: fixed; z-index: 1; top: 250px; left: 0;">
    <a class="nav-link active" id="map-tab" data-toggle="tab" href="#map" role="tab" aria-controls="map" aria-selected="true">
      <i class="fas fa-map-marker-alt"></i>
    </a>
  </li>
  <li class="nav-item nav-time bg-white" style="position: fixed; z-index: 1; top: 300px; left: 0;">
    <a class="nav-link" id="time-tab" data-toggle="tab" href="#time" role="tab" aria-controls="time" aria-selected="true">
      <i class="far fa-clock"></i>
    </a>
  </li>
</ul>

<div class="tab-content" id="myTabContent">
  <!-- map -->
  <div class="tab-pane fade show active" id="map" role="tabpanel" aria-labelledby="map-tab">
    <div id="sample"></div>
  </div>

  <!-- timeline -->
  <div class="tab-pane fade pt-5" id="time" role="tabpanel" aria-labelledby="time-tab">
    <div class="container post-index jscroll">
      <% @scroll_posts.each do |scroll_post| %>
        <div class="post-content mb-4 row mx-auto p-3">

          <div class="col-lg-4">
            <img src='<%= scroll_post.artwork %>' width="150px" height="150px" alt="artiwork" style="border: 1px solid #ddd">
            <p class="map-info-time"><%= scroll_post.created_at.strftime('%Y年%m月%d日 %H時%M分') %></p>
          </div>
          <div class="col-lg-6 col-lg-offset-2">
            <%= link_to scroll_post.songs_title, proust_show_path(scroll_post.id), :class=> "md-1 h2 text-dark" %>
            <p class="mb-2"><%= scroll_post.artist %></p>
            <p class="mb-2 post-address"><%= scroll_post.address %></p>
            <p><%= scroll_post.body %></p>
          </div>
        </div>
      <% end %>
      <%= paginate @scroll_posts%>
    </div>
  </div>
</div>

<!-- rec button -->
<div class="loader" id="animation" style="display: none;">
  <div class="dot"></div>
  <div class="dot"></div>
  <div class="dot"></div>
</div>

<div class="rec" id="stay" onClick="startRec();">
  <div class="stay_dot"></div>
  <div class="stay_dot"></div>
  <div class="stay_dot"></div>
</div>

<script>
// 時間フォーマット
var formatDate = function (date, format) {
  if (!format) format = 'YYYY-MM-DD hh:mm:ss.SSS';
    format = format.replace(/YYYY/g, date.getFullYear());
    format = format.replace(/MM/g, ('0' + (date.getMonth() + 1)).slice(-2));
    format = format.replace(/DD/g, ('0' + date.getDate()).slice(-2));
    format = format.replace(/hh/g, ('0' + date.getHours()).slice(-2));
    format = format.replace(/mm/g, ('0' + date.getMinutes()).slice(-2));
    format = format.replace(/ss/g, ('0' + date.getSeconds()).slice(-2));
  if (format.match(/S/g)) {
    var milliSeconds = ('00' + date.getMilliseconds()).slice(-3);
    var length = format.match(/S/g).length;
    for (var i = 0; i < length; i++) format = format.replace(/S/, milliSeconds.substring(i, i + 1));
  }
  return format;
};

///////////////////////////マップ表示/////////////////////////////////
var map;
var marker = [];
var infoWindow = [];
var postInfomation = {};

// 一度もマッピングされていない時に使われる経緯度
var markerData = [
  {
       lat: 35.6954806,
        lng: 139.76325010000005,
  }
];

//mapの作成
if (gon.post === null) {
  function initMap() {
    var mapLatLng = new google.maps.LatLng({lat: markerData[0]['lat'], lng: markerData[0]['lng']});
    map = new google.maps.Map(document.getElementById('sample'), {
      center: mapLatLng,
      zoom: 5
    });
  }
} else {
  function initMap() {
    var mapLatLng = new google.maps.LatLng({lat: gon.post['latitude'], lng: gon.post['longitude']});
    map = new google.maps.Map(document.getElementById('sample'), {
      center: mapLatLng,
      zoom: 12
    });

    for (var i = 0; i < gon.posts.length; i++) {
      markerLatLng = new google.maps.LatLng({ lat: gon.posts[i]['latitude'], lng: gon.posts[i]['longitude'] }); // 緯度経度のデータ作成
      marker[i] = new google.maps.Marker({ // マーカーの追加
        position: markerLatLng, // マーカーを立てる位置を指定
        map: map // マーカーを立てる地図を指定
      });


      infoWindow[i] = new google.maps.InfoWindow({ // 吹き出しの追加
        content: '<div class="info-window" style="width:400;">' + '<p class="mb-1 map-info-time">' +   + '</p>' + '<p>' + gon.posts[i]['address'] + '</p>' + '<div class="mx-auto text-center">' +'<section class="d-inline-block">'+ `<a href='/prousts/${gon.posts[i]["id"]}/show' class='map-info-song-title d-block h2'>` + gon.posts[i]['songs_title'] + '</a>' + '<img src="' + gon.posts[i]['artwork'] + '" width="200" height="200" alt="artwork">' +'</section>'+ '</div>' + '<p class="py-3 mt-2" style="border: 3px solid #c0c0c0; ">' + gon.posts[i]['body'] + '</p>' +'</div>' // 吹き出しに表示する内容
      });

      markerEvent(i); // マーカーにクリックイベントを追加
    }
  }
}


// マーカーにクリックイベントを追加
var currentInfoWindow = null;
function markerEvent(i) {
  marker[i].addListener('click', function() { // マーカーをクリックしたとき
    if (currentInfoWindow) {
      currentInfoWindow.close();
    }
    //情報ウィンドウを開く
    infoWindow[i].open(map, marker[i]); // 吹き出しの表示
    currentInfoWindow = infoWindow[i];
  });
}

initMap();



/////////////////////////レコーディング///////////////////////////////
let audio_sample_rate = null;
let scriptProcessor = null;
let audioContext = null;

// audio data
let audioData = [];
let bufferSize = 1024;

let url = "";

let saveAudio = function () {

  var blob = exportWAV(audioData);

  var fd = new FormData();
  fd.append('file', blob, (new Date()).getTime() + ".wav");

  $(document).ajaxStop(function() {
    $('#animation').hide();
    $('#stay').show();
  });

  if(location.href.indexOf("proust.tokyo") > -1) {
    url = "https://proust.tokyo/prousts/convert"
  } else {
    url = "http://localhost:3000/prousts/convert"
  }

  $.ajax({
    url:url,
    type:'POST',
    data:fd,
    contentType: false,
    processData: false,
  })

  // Ajaxリクエストが成功した時発動
  .done( (data) => {

    console.log(data);
    getCurrentPosition(data);
    // alert("データの取得に成功しました。");
  })
  // Ajaxリクエストが失敗した時発動
  .fail( (data) => {
      alert("データの取得に失敗しました。");
  })
  // Ajaxリクエストが成功・失敗どちらでも発動
  .always( (data) => {
    audioData = [];
  });

}

let exportWAV = function (audioData) {

  let encodeWAV = function (samples, sampleRate) {
    let buffer = new ArrayBuffer(44 + samples.length * 2);
    let view = new DataView(buffer);

    let writeString = function (view, offset, string) {
      for (let i = 0; i < string.length; i++) {
        view.setUint8(offset + i, string.charCodeAt(i));
      }
    };

    let floatTo16BitPCM = function (output, offset, input) {
      for (let i = 0; i < input.length; i++ , offset += 2) {
        let s = Math.max(-1, Math.min(1, input[i]));
        output.setInt16(offset, s < 0 ? s * 0x8000 : s * 0x7FFF, true);
      }
    };

    writeString(view, 0, 'RIFF');  // RIFFヘッダ
    view.setUint32(4, 32 + samples.length * 2, true); // これ以降のファイルサイズ
    writeString(view, 8, 'WAVE'); // WAVEヘッダ
    writeString(view, 12, 'fmt '); // fmtチャンク
    view.setUint32(16, 16, true); // fmtチャンクのバイト数
    view.setUint16(20, 1, true); // フォーマットID
    view.setUint16(22, 1, true); // チャンネル数
    view.setUint32(24, sampleRate, true); // サンプリングレート
    view.setUint32(28, sampleRate * 2, true); // データ速度
    view.setUint16(32, 2, true); // ブロックサイズ
    view.setUint16(34, 16, true); // サンプルあたりのビット数
    writeString(view, 36, 'data'); // dataチャンク
    view.setUint32(40, samples.length * 2, true); // 波形データのバイト数
    floatTo16BitPCM(view, 44, samples); // 波形データ

    return view;
  };

  let mergeBuffers = function (audioData) {
    let sampleLength = 0;
    for (let i = 0; i < audioData.length; i++) {
      sampleLength += audioData[i].length;
    }
    let samples = new Float32Array(sampleLength);
    let sampleIdx = 0;
    for (let i = 0; i < audioData.length; i++) {
      for (let j = 0; j < audioData[i].length; j++) {
        samples[sampleIdx] = audioData[i][j];
        sampleIdx++;
      }
    }
    return samples;
  };

  let dataview = encodeWAV(mergeBuffers(audioData), audio_sample_rate);
  let audioBlob = new Blob([dataview], { type: 'audio/wav' });

  return audioBlob;
};

// save audio data
var onAudioProcess = function (e) {
  var input = e.inputBuffer.getChannelData(0);
  var bufferData = new Float32Array(bufferSize);
  for (var i = 0; i < bufferSize; i++) {
    bufferData[i] = input[i];
  }

  audioData.push(bufferData);
};

// getusermedia
let handleSuccess = function (stream) {
  audioContext = new(window.AudioContext || window.webkitAudioContext);
  audio_sample_rate = audioContext.sampleRate;
  scriptProcessor = audioContext.createScriptProcessor(bufferSize, 1, 1);
  var mediastreamsource = audioContext.createMediaStreamSource(stream);
  mediastreamsource.connect(scriptProcessor);
  scriptProcessor.onaudioprocess = onAudioProcess;
  scriptProcessor.connect(audioContext.destination);

  setTimeout(function () {
    mediastreamsource.disconnect(scriptProcessor);
    scriptProcessor.disconnect(audioContext.destination);
    saveAudio();
  }, 5000);
};

function startRec(){
  navigator.mediaDevices.getUserMedia({ audio: true, video: false }).then(handleSuccess);
  var stay_dot = document.getElementById("stay");
  stay_dot.style.display = "none";
  var animation_dot = document.getElementById("animation");
  animation_dot.style.display = "block";
}


/////////////////////////////現在地取得////////////////////////////////////

function getCurrentPosition(data) {
  if (data == null || data.result == null) {
    alert("曲がヒットしませんでした");
    return;
  }

  ////////paramsの値を設定//////////
  var songs_title = data.result.title;
  var album = data.result.album;
  var release_date = data.result.release_date;
  var artist = data.result.artist

  var artwork = ""
  var youtube_link = ""

  if (data.result["spotify"]) {
    var artwork = data.result.spotify.album.images[0].url;
  }

  if (data.result.lyrics) {
    var youtube_links = JSON.parse(data.result.lyrics.media);
    for (var i=0; i< youtube_links.length; i++){
      if (youtube_links[i].provider == "youtube") {
        var youtube_link = youtube_links[i].url;
      }
    }
  }
///////////////////////////////////

  'use strict';
  if( navigator.geolocation ){

    navigator.geolocation.getCurrentPosition(success, error, option);
    /*現在位置が取得できた時に実行*/
    function success(position){
      var data = position.coords;
      // 必要な緯度経度だけ取得
      var lat = data.latitude;
      var lng = data.longitude;
      //Google Mapsで住所を取得
      var geocoder = new google.maps.Geocoder();
      var latlng = new google.maps.LatLng(lat, lng);
      geocoder.geocode({'latLng': latlng}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          // document.getElementById('address').innerHTML = results[0].formatted_address;
          window.location.href = `/prousts/new?address=${results[0].formatted_address}&latitude=${lat}&longitude=${lng}&songs_title=${songs_title}&album=${album}&artist=${artist}&release_date=${release_date}&artwork=${artwork}&youtube_link=${youtube_link}`;
          }
        else {
          alert("エラー" + status);
        }
      });
    }
    /*現在位置の取得に失敗した時に実行*/
    function error(error){
      var errorMessage = {
      0: "原因不明のエラーが発生しました。",
      1: "位置情報が許可されませんでした。",
      2: "位置情報が取得できませんでした。",
      3: "タイムアウトしました。",
      } ;
      //とりあえずalert
      alert(errorMessage[error.code]);
    }
    // オプション(省略可)
    var option = {
      "enableHighAccuracy": false,
      "timeout": 100 ,
      "maximumAge": 100 ,
    } ;
  } else {// 現在位置を取得できない場合の処理
  //とりあえずalert
    alert("あなたの端末では、現在位置を取得できません。");
  }
}

////////////////無限スクロール実装//////////////////////////////
$(function() {
  $('.jscroll').jscroll({
    contentSelector: '.post-index',
    nextSelector: 'span.next:last a'
  });
});


</script>

app/views/prousts/new.html.erb
<%= render "shared/header_user_after_signin" %>

<% if @params_post_info.errors.any? %>
<h3><%= @params_post_info.errors.count %>errors prohibited this obj from being saved:</h3>
<ul>
  <% @params_post_info.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>
<% end %>

<div class="container-fluid">
  <div class="row d-flex align-items-center new-post-wrapper">

    <div class="col-xl-4 p-0">
      <div class="image-wrapper text-center">
        <img src='<%= @params_post_artwork%>' width="350" height="350" alt="artiwork" class="d-inline-block"><br>
      </div>
    </div>
    <div class="col-xl-7 col-xl-offset-2">
      <%= form_with(model: @params_post_info, url: proust_path, local: true, :class => 'post-form mx-auto') do |f| %>

        <div class="song-item">

            <span class="song-title font-weight-bold" style="border-bottom: 1px solid #000"><em>Song</em></span>

          <%= f.hidden_field :songs_title, autofocus: true, :value => @params_post_songs_title %>
          <h5 class="song-element mt-1"><%= @params_post_songs_title %></h5>

          <%= f.hidden_field :artist, :value => @params_post_artist %>
          <p class="song-element text-left"><%= @params_post_artist %></p>

          <%= f.hidden_field :artwork, :value => @params_post_artwork %>
          <%= f.hidden_field :album, :value => @params_post_album %>
          <%= f.hidden_field :relese_date, :value => @params_post_release_date %>
          <%= f.hidden_field :youtube_link, :value => @params_post_youtube_link %>
        </div>

        <div class="address-item">
          <%= f.hidden_field :address, :value => @params_post_address %>

            <span class="font-weight-bold address-title" style="border-bottom: 1px solid #000"><em>Address</em></span>

          <p><%= @params_post_address %></p>

          <%= f.hidden_field :latitude, :value => @params_post_latitude %>
          <%= f.hidden_field :longitude, :value => @params_post_longitude %>
        </div>

        <div class="post-item">
            <span class="font-weight-bold post-title" style="border-bottom: 1px solid #000">
              <em><%= f.label :body, "Proust" %></em>
            </span>
          <%= f.text_area :body, autofocus: true %><br>

          <%= f.attachment_field :post_image %><br>

          <%= f.submit "投稿", :class => "btn btn-primary post-btn" %><br>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/prousts/show.html.erb
<%= render "shared/header_user_after_signin" %>

<div class="container mt-5">
  <div style="padding: 30px; border-radius: 30px; background-color: #eee;">
    <div class="row mb-3 justify-content-center">
<!-- modal -->
      <div class="col-lg-3">
        <img src="<%= @post.artwork %>" width="200" height="200" alt="artiwork" style="border-radius: 100%;">
      </div>
      <div class="col-lg-7 col-lg-offset-2" style="vertical-align: middle;">
        <div>
          <h2 class="d-inline-block"><%= @post.songs_title %></h2>
          <i id="ellipsis-menu" class="fas fa-ellipsis-v d-block" style="font-size: 28px; float: right; margin: 8px 30px 0 0; position: relative; width: 100px;">
            <div class="modal-menu modal-hidden show-modal" style="position: absolute; top: -5px; left: -30px; z-index: 10;">
              <%= link_to proust_delete_path(@post.id), method: :delete, "data-confirm" => "本当に投稿を削除しますか？", :class => "btn delete-button" do %><i class="far fa-trash-alt text-danger">  削除</i>
              <% end %>
            </div>
          </i>
        </div>
        <p class="mb-1"><%= @post.artist %></p>
        <% if !@post.youtube_link.empty? %>
          <p class="mb-0" style="font-size: 13px;">To Youtube</p>
          <p class="mb-4"><a href='<%= @post.youtube_link %>' target="_blank"><%= @post.youtube_link %></a></p>
        <% end %>
        <% if @video_id %>
          <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @video_id %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <% end %>
        <p><%= @post.address %></p>
        <% if !@common_posts.empty? %>
          <p><%= link_to "Proust Friends!", "/prousts/#{@post.id}/common_posts_index" %></p>
        <% end %>
      </div>
    </div>

    <div class="card mx-auto" style="width: 55vw; height: auto;">
      <% if @post.post_image_id %>
      <%= image_tag attachment_url(@post, :post_image, :fill, 650, 406, format: "jpg"), :style => "height: auto", :class => "card-img-top" %>
      <% end %>
      <div class="card-body">
        <p class="card-text"><%= @post.body %></p>
      </div>
    </div>
  </div>
</div>

<div class=" overlay overlay-hidden overlay-size" style="z-index: 5; position: fixed">
</div>

<!-- モーダル -->

<script>

  $('#ellipsis-menu').click(function() {
    $('.modal-menu').removeClass('modal-hidden');
    $('.overlay').removeClass('overlay-hidden');
  })

  $('.overlay').click(function() {
    $('.modal-menu').addClass('modal-hidden');
    $('.overlay').addClass('overlay-hidden');
  })

</script>


<style>
.delete-button{
  background-color: #eee;
}

.modal-hidden {
  display: none;
}

.overlay-hidden {
  display: none;
}

.overlay-size {
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
}
</style>